### ISSUE TITLE
Support Installed code via python callable string

### ISSUE THREAD

**Issue by john-drews** [astronomer/dag-factory#220]
i want to be able to define a path to a custom function that i am installing into my airflow environment. This will allow me to test my dag locally without having to define a path and simply refer to the package path instead.

Example

```yaml
        branch_by_bq_load_status:
            operator: airflow.operators.python.BranchPythonOperator
            python_callable: custom.path.to.func

```
