### ISSUE TITLE
Make DAG Factory compatible with Airflow 3.0

### ISSUE THREAD

**Issue by tatiana** [astronomer/dag-factory#224]
By January 2025, we'll have Airflow 3.0 alpha releases.
We need to make sure DAG Factory will be compatible with this new version of Airflow

**Comment by palakkal** [comment]
@pankajastro do you have a timeline for when this feature will be available?

**Comment by VinilKumarReddy** [comment]
@pankajastro , I tried using pre release in my local 0.23.0a7, But the dag building got failed with error. It is getting schedule_interval keyword from somewhere. However, in my yml, I dont have schedule_interval mentioned. 
**YML file**:

<img width="620" height="425" alt="Image" src="https://github.com/user-attachments/assets/7d8094c4-aa65-44e9-8a16-9b603a574dab" />

**Error:**
_Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/dagfactory/dagfactory.py", line 173, in build_dags
    dag: Dict[str, Union[str, DAG]] = dag_builder.build()
                                      ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dagfactory/dagbuilder.py", line 946, in build
    dag: DAG = DAG(**dag_kwargs)
               ^^^^^^^^^^^^^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'schedule_interval'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/dagfactory/dagfactory.py", line 209, in clean_dags
    dags: Dict[str, Any] = self.build_dags()
                           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dagfactory/dagfactory.py", line 176, in build_dags
    raise DagFactoryException(f"Failed to generate dag {dag_name}: {err}") from err
dagfactory.exceptions.DagFactoryException: Failed to generate dag dagtestyml: DAG.__init__() got an unexpected keyword argument 'schedule_interval'_

**Comment by pankajastro** [comment]
@VinilKumarReddy, your current YAML is not compatible with Airflow 3. We are working on providing some examples in the PR: https://github.com/astronomer/dag-factory/pull/457 and possibly a method to make the Airflow 2 YAML DAG compatible with Airflow 3. In the meantime, you can try below DAG, which is functionally equivalent to your existing one.

```
default:
  default_args:
    catchup: false
    start_date: 2025-01-01

basic:
  default_args:
    owner: "custom_owner"
  description: "this is an example dag"
  schedule: "0 3 * * *"
  render_template_as_native_obj: True
  tasks:
    task_1:
      operator: airflow.providers.standard.operators.bash.BashOperator
      bash_command: "echo 1"
    task_2:
      operator: airflow.providers.standard.operators.bash.BashOperator
      bash_command: "echo 2"
      dependencies: [task_1]
    task_3:
      operator: airflow.providers.standard.operators.bash.BashOperator
      bash_command: "echo 2"
      dependencies: [task_1]
```
