### ISSUE TITLE
Expand() usage does not pickup .output if task with expand comes before in yaml def/dict keys of task referenced in expand

### ISSUE THREAD

**Issue by StephenOTT** [astronomer/dag-factory#225]
If you have something like 

```
Tasks:
   Task1:
      ...
      Dependencies: [Task2]
      Expand: 
         Some_arg: Task2.output

   Task2:
      ...
```

Then when dagbuilder parses the tank/duct is does not properly change the expand arg to a referenced Xcom and it remains as a are
