### ISSUE TITLE
Support dag_display_name property

### ISSUE THREAD

**Issue by aliellis** [astronomer/dag-factory#233]
Hi there, correct me if im wrong but dag-factory doesn't seem to support the [dag_display_name](https://airflow.apache.org/docs/apache-airflow/stable/_modules/airflow/example_dags/example_display_name.html) property?

expected config/behaviour:
```yaml
example_dag:
  default_args:
    owner: "a-person"
    start_date: '2024-10-08'
  schedule_interval: None
  catchup: False
  description: 'Responsible for running an example DAG'
  dag_display_name: "Pretty Example DAG"
  ```

We then get a DAG called "Pretty Example DAG" not "example_dag"

Looks like it can be tagged on anywhere around [here](https://github.com/astronomer/dag-factory/blob/main/dagfactory/dagbuilder.py#L675-L681)? Happy to submit an MR if thats the case :)
