### ISSUE TITLE
[Feature] Add Support for Dynamic DAG Generation with Templating

### ISSUE THREAD

**Issue by jroach-astronomer** [astronomer/dag-factory#280]
### Description

Within a `.yml` file, allow for for a template-variable pattern to be used for defining DAGs. For example, this might look something like this:

```yaml
<< dag_id >>:
  start_date: << start_date >>
  ...
  tasks:
    start:
      operator: airflow.operators.python.PythonOperator
      python_callable_file: include.helpers
      python_callable_name: my_function
      op_kwargs:
        param1: << param1 >>


variables:
  dag_id: dag_a
    - start_date: "2024-01-01"
    - param1: "Alpha"
  dag_id: dag_b
    - start_date: "2024-02-01"
    - param1: "Bravo"
...
```

This could also be something that is done in the `.py` file when defining the `DagFactory` class.

### Use case/motivation

Allow for a DAG to truly be created "dynamically" using `dag-factory`. In this scenario, the `.yml` file can truly be used as a template file, with parameters passed in via the `.yml` file or when defining the `DagFactory` class.

### Are you willing to submit a PR?

- [x] Yes, I am willing to submit a PR!
