### ISSUE TITLE
[Feature] Shared defaults for load_yaml_dags

### ISSUE THREAD

**Issue by wearpants** [astronomer/dag-factory#297]
### Description

It'd be nice to pass some shared `default_args` for a directory, either via a python object or a `defaults.yml` file in the directory.

### Use case/motivation

One DAG per file is easier for users IMO, and as a system administrator I'd like to be able to give them a shared set of pre-baked defaults (env vars, etc.)

### Related issues

#289, #290 

### Are you willing to submit a PR?

- [x] Yes, I am willing to submit a PR!

**Comment by cmarteepants** [comment]
Something like this?

./dags/default.yml
``` 
default:
  catchup: false
  default_args:
    start_date: "2024-01-01"
  schedule_interval: "0 0 * * *"
  tasks:
    extract:
      operator: airflow.operators.python.PythonOperator
      python_callable_file: /usr/local/airflow/include/etl_helpers.py
      python_callable_name: extract_helper
    load:
      dependencies:
      - transform
      operator: airflow.operators.python.PythonOperator
      python_callable_file: /usr/local/airflow/include/etl_helpers.py
      python_callable_name: load_helper
    transform:
      dependencies:
      - extract
      op_kwargs:
        ds_nodash: '{{ds_nodash}}'
      operator: airflow.operators.python.PythonOperator
      python_callable_file: /usr/local/airflow/include/etl_helpers.py
      python_callable_name: transform_helper
```

./dags/bi.yml
``` 
business_analytics:
  schedule_interval: "@daily"
  tasks:
    load:
      op_kwargs:
        database_name: BA
        table_name: inventory
```

./dags/ds.yml
```
data_science:
  tasks:
    load:
      op_kwargs:
        database_name: DS
        table_name: daily_sales
```

./dags/ml.yml
```
machine_learning:
  tasks:
    load:
      op_kwargs:
        database_name: ML
        table_name: training_data
```
...
