### ISSUE TITLE
[Bug] Expand on Multiple Parameters Not Supported in Dynamic Task Mapping

### ISSUE THREAD

**Issue by su-four** [astronomer/dag-factory#301]
### DAG Factory version

0.20.0

### airflow version

2.10

### Python version

3.12

### Deployment

Docker-Compose

### What happened?

The dag-factory library currently does not support the expand feature for multiple parameters in Airflow's dynamic task mapping. When specifying multiple parameters in the expand field, such as op_args using multiple outputs from upstream tasks, the second parameter is not parsed or replaced with the actual task output.

Expected Behavior:
The dag-factory library should replace both third.output and forth.output with the actual outputs from the respective tasks (third and forth) and pass them correctly to the task five. [how airflow do this](https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/dynamic-task-mapping.html#mapping-over-multiple-parameters) 

Actual Behavior:
Only the first parameter (third.output) is parsed and replaced. The second parameter (forth.output) remains unchanged and is not recognized as a valid dynamic mapping.

### How to reproduce

For example, when defining an operator in the YAML configuration like this:

```
five:  
  operator: "airflow.operators.python.PythonOperator"  
  python_callable_name: "five"  
  python_callable_file: "/funcs/test.py"  
  expand:  
    op_args: [third.output, forth.output]  
  dependencies: [third, forth]  
```
You can observe that the second parameter (forth.output) is not replaced or parsed correctly. The expected behavior is for both third.output and forth.output to resolve to the actual outputs of the third and forth tasks, respectively. However, only third.output is parsed and replaced, while forth.output remains unchanged, causing the operator to fail or behave unexpectedly.

### Anything else :)?

This issue impacts workflows that rely on passing multiple outputs to a single downstream task, a key feature of Airflow's dynamic task mapping.
