### ISSUE TITLE
[Bug] `partial` Does Not Replace Task Outputs

### ISSUE THREAD

**Issue by su-four** [astronomer/dag-factory#303]
### DAG Factory version

0.20.0

### airflow version

2.10

### Python version

3.12

### Deployment

Docker-Compose

### What happened?

When using the partial feature in dag-factory to define task parameters that depend on the output of a previous task, the output of the upstream task is not replaced with its actual value.

### Relevant log output

```shell

```

### How to reproduce

For example, consider the following YAML configuration:
```
five:  
  operator: "airflow.operators.python.PythonOperator"  
  python_callable_name: "five"  
  python_callable_file: "/funcs/test.py"  
  partial:  
    input: third.output  
  dependencies: [third]
```
Here, the input parameter in partial is expected to be replaced with the actual output of the third task. However, `third.output` is not resolved and remains as-is, causing the task five to behave incorrectly.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by tatiana** [comment]
Hi, @su-four. Thank you for reporting this issue.

Unfortunately, with the details you shared, we could not reproduce the bug.

Currently, DAG factory has an example DAG and configuration file that works with task mapping:
https://github.com/astronomer/dag-factory/blob/main/dev/dags/example_task_group.py
https://github.com/astronomer/dag-factory/blob/main/dev/dags/example_task_group.yml

It uses the functions defined in:
https://github.com/astronomer/dag-factory/blob/main/dev/dags/expand_tasks.py

And it seems to work as expected. Please, could you modify this example to reproduce the bug you're facing, and share with us all the changes necessary to be able to reproduce it?

**Comment by su-four** [comment]
# Clarification on Earlier Report:
Hi, @tatiana and team!

Thank you for your response. I realize that I may have miscommunicated my original issue and possibly gave the wrong impression. Let me clarify:


I am not using dynamic task mapping in this scenario. Instead, I am trying to pass the output of one task (e.g., task1) as an input to another task (e.g., task2) directly within the DAG Factory YAML configuration. However, it seems that placeholders like task1.output are not being resolved to the actual output of the upstream task.



## Example Configuration:
Here’s a simplified configuration to illustrate my problem:


```yaml
Copy code
tasks:
  task1:
    operator: "airflow.operators.python.PythonOperator"
    python_callable_name: "task1"
    python_callable_file: "/funcs/task1.py"
  
  task2:
    operator: "airflow.operators.python.PythonOperator"
    python_callable_name: "task2"
    python_callable_file: "/funcs/task2.py"
    partial:
      input: task1.output
    dependencies: [task1]
```


### Expected Behavior:
task1 generates an output (e.g., result1).
task2 should receive result1 as the value for the input parameter via the partial configuration.

### Actual Behavior:
The placeholder task1.output in the partial configuration is not replaced with the actual value from task1's output.
As a result, task2 either fails or operates on an unresolved placeholder.
## Additional Example:
I also tried this configuration, and as expected, it also doesn’t work:


```yaml
Copy code
tasks:
  num_genrator:
    operator: "airflow.operators.python.PythonOperator"
    python_callable_name: "task1"
    python_callable_file: "/funcs/task1.py"
  
  task2:
    operator: "airflow.operators.python.PythonOperator"
    python_callable_name: "task2"
    python_callable_file: "/funcs/task2.py"
    num_list: num_genrator.output
    dependencies: [num_genrator]
```


In this case, I attempted to pass the output of the num_genrator task directly to the num_list parameter of task2. However, the placeholder num_genrator.output also remained unresolved.

**Comment by pankajastro** [comment]
Hey @su-four, could you please share an example of a Python DAG that aligns with the one you provided above?

Here's an example of how you can access XCom. This achieves the same result as `task.output`.

I understand that `task.output` feels cleaner and more intuitive for writing DAGs compared to using `{{ task_instance.xcom_pull(task_ids='*') }}`, but that would introduce a performance overhead since the `task.output` string has to be replaced with XComArg during runtime.

example_xcom.yml
```
test_output:
  default_args:
    owner: "custom_owner"
    start_date: 2 days
  schedule_interval: "0 3 * * *"
  default_view: "graph"
  tasks:
    process:
      operator: airflow.operators.python_operator.PythonOperator
      python_callable_name: consume_value
      python_callable_file: $CONFIG_ROOT_DIR/tasks_call.py
      op_kwargs:
        fixed_param: "{{ task_instance.xcom_pull(task_ids='request') }}"
      dependencies: [request]
    request:
      operator: airflow.operators.python.PythonOperator
      python_callable_name: return_val
      python_callable_file: $CONFIG_ROOT_DIR/expand_tasks.py
```
example_xcom.py

```python
import os
from pathlib import Path

# The following import is here so Airflow parses this file
# from airflow import DAG
import dagfactory

DEFAULT_CONFIG_ROOT_DIR = "/usr/local/airflow/dags/"

CONFIG_ROOT_DIR = Path(os.getenv("CONFIG_ROOT_DIR", DEFAULT_CONFIG_ROOT_DIR))

config_file = str(CONFIG_ROOT_DIR / "example_xcom.yml")

example_dag_factory = dagfactory.DagFactory(config_file)

# Creating task dependencies
example_dag_factory.clean_dags(globals())
example_dag_factory.generate_dags(globals())

```
tasks_call.py

```python
def return_val():
    return 2


def consume_value(fixed_param, **kwargs):
    print(fixed_param)
```
