### ISSUE TITLE
[Bug] Issue with HttpOperator Data Handling in DAGFactory

### ISSUE THREAD

**Issue by a-chumagin** [astronomer/dag-factory#370]
### DAG Factory version

0.22.0

### airflow version

2.10.2

### Python version

3.12

### Deployment

Docker-Compose

### What happened?

I am experiencing an issue when using dag-factory to configure HttpOperator tasks. The request body is incorrectly serialized, and the content type is being treated as form data instead of JSON. This issue occurs only when the task is created via DAGFactory, but works fine when using raw HttpOperator code.

### Relevant log output

```shell

```

### How to reproduce

1. Create a DAG using DAGFactory with an HttpOperator task that sends JSON data.
2. Ensure the data is correctly formatted as a JSON string (e.g., data: '{"data_source": "postgres"}').
3. When the task runs, check the request body sent to the HTTP endpoint.
4. The body is sent as form-encoded data (e.g., data_source=postgres), not as JSON.

**Expected Behavior:**
The request body should be serialized as valid JSON and sent with the Content-Type: application/json header.

**Actual Behavior:**
The body is sent as form data (e.g., data_source=postgres), not as JSON. This causes the request to fail.

Example of YAML
```
basic_example_dag:
  default_args:
    owner: "@a.chumagin"
  description: "this is an example dag"
  schedule_interval: "0 3 * * *"
  tags: ['dqa']
  render_template_as_native_obj: True
  tasks:
    send_request:
      operator: airflow.providers.http.operators.http.HttpOperator
      http_conn_id: "dqp_host_dev"
      method: "POST"
      endpoint: "/run_test"
      data: '{"data_source": "postgres"}'
      headers:
        Content-Type: application/json
      log_response: True
```

The headers send correct . I use echo service for handle request 
```
POST /run_test HTTP/1.1
Host: echo-local.com:8087
Accept: */*
Accept-Encoding: gzip, deflate
Content-Length: 20
Content-Type: application/json
User-Agent: Python/3.12 aiohttp/3.10.5
data_source=postgres
```

I tried different ways to present data 
1. As dictionary 
```
   data: 
          data_source: "postgres"
```
2. With """ and > wrappers. Same result

When I use raw HttpOperator without DagFactory the issues does not occur 
```
HttpOperator(task_id='http_soda_check',
                                   http_conn_id='dqp_host_dev',
                                    method='POST',
                                    endpoint="/run_test",
                                    data="""
                                    {
                                    "data_source": "postgres"
                                   }
                                   """,
                                headers={"Content-Type": "application/json"},
                                   log_response=True ,
                                )
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
