### ISSUE TITLE
Support for user-defined complex property types in YAML (e.g., !!k8s.V1ResourceRequirements)

### ISSUE THREAD

**Issue by pankajastro** [astronomer/dag-factory#426]
Enable end-users to explicitly define the "type" of complex properties in YAML configuration files using Python class annotations. This will help in scenarios where users want to override advanced objects (e.g., Kubernetes client models like k8s.V1ResourceRequirements) that need to be declared in configuration files and parsed into specific Python types.

### Example Use Case

```yaml
container_resources: !!k8s.V1ResourceRequirements
  - requests
    - cpu: "1000m"
    - memory: "8G"
  - limits
    - cpu: "16000m"
    - memory: "128G"
```
This should be parsed and instantiated as a k8s.V1ResourceRequirements object with the corresponding fields populated.

Possible Solution. 

Add a mechanism for YAML deserialization to recognise and instantiate tagged Python objects using the `!!module.ClassName` syntax.
